apiVersion: v1
kind: Pod
metadata:
  name: kali
  namespace: kali
  labels:
    app: kali
spec:
  containers:
  - name: kali
    image: kalilinux/kali-rolling
    command:
        - "/bin/sleep"
        - "10000"
  dnsPolicy: ClusterFirst