apiVersion: v1
kind: Pod
metadata:
  name: kali2
  namespace: kali2
  labels:
    app: kali2
spec:
  containers:
  - name: kali2
    image: kalilinux/kali-rolling
    command:
        - "/bin/sleep"
        - "10000"
  dnsPolicy: ClusterFirst