apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx2
    namespace: ngi
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8888
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx2
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""