apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: udpsrv
    namespace: ngi
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 6000
      protocol: UDP
      targetPort: 6000
    selector:
      app: udpsrv
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""